# Generated by Django 4.2.2 on 2023-06-23 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('urb', 'Urbano'), ('rur', 'Rural')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numVivienda', models.IntegerField()),
                ('numParques', models.CharField(choices=[('uno', '1'), ('dos', '2'), ('tres', '3'), ('cuatro', '4'), ('cinco', '5'), ('seis', '6')], max_length=30)),
                ('numEdificios', models.IntegerField()),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasparroquias', to='ordenamiento.parroquia')),
            ],
        ),
    ]
